version: '3.1'

services:

  redmine:
    image: redmine:5.0.0
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: mysqlpwd
      REDMINE_SECRET_KEY_BASE: my-redmine-supersecret-key

  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpwd
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_HOST: '%'